In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_train = pd.read_csv("data_train.csv")

In [3]:
data_train_cat = data_train.select_dtypes(include =  ["object"])

In [4]:
data_train_num = data_train.select_dtypes(exclude =  ["object"])

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
data_train_num

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [7]:
data_train_cat

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [8]:
data_train_cat.sample(1)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
415,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,New,Partial

In [9]:
data_train.Id.isna().sum()

0

In [10]:
cat = []
for col in data_train.columns:
    if data_train[col].isna().sum() > 500:
        cat.append(col)
print(cat)

['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']

In [11]:
data_train.drop(columns = cat, axis = 1, inplace = True)

### Handling the missing values:
two types  i.e is by replacing with mean value.

In [12]:
if data_train.Street.dtype == 'O':
    print(True)

True

In [13]:

data_train.OverallQual.dtype == 'int64'
#     print(True)

True

In [14]:
for col in missing_columns:
    if data_train[col].dtype == 'O':
        data_train[col].fillna(data_train[col].value_counts().sort_values().index[-1], inplace = True)
    else:
         data_train[col].fillna(np.round(data_train[col].mean(),0), inplace = True)

NameError: name 'missing_columns' is not defined

### Separating the category and integer values :

In [ ]:
data_train_cat = data_train.select_dtypes(include =  ["object"])

In [ ]:
missing_columns = []
for col in data_train.columns:
    if data_train[col].isna().sum() > 0:
        missing_columns.append(col)
# print(missing_columns)
# missing_data = data_train[[missing_columns]]

### Identifying the cat columns and int columns

In [ ]:
missing_columns

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# set = {}
for col in data_train_cat.columns:
    le = LabelEncoder()
#     set[col] = le.fit(data_train_cat[col])
    data_train[col+"_num"] = le.fit_transform(data_train_cat[col])
#     print(col)

In [ ]:
new_train_data = data_train.select_dtypes(exclude = ['object'])

In [ ]:
trainX = new_train_data.drop(columns = ['SalePrice'])

In [ ]:
trainY = new_train_data.SalePrice

In [ ]:
data_test = pd.read_csv('data_test.csv')

In [ ]:
cat = []
for col in data_test.columns:
    if data_test[col].isna().sum() > 500:
        cat.append(col)
print(cat)

In [ ]:
data_test.drop(columns = cat, axis = 1, inplace = True)

In [ ]:
missing_column = []
for col in data_test.columns:
    if data_test[col].isna().sum() > 0:
        missing_column.append(col)
# print(missing_columns)
# missing_data = data_train[[missing_columns]]

In [ ]:
for col in missing_column:
    if data_test[col].dtype == 'O':
        data_test[col].fillna(data_test[col].value_counts().sort_values().index[-1], inplace = True)
    else:
         data_test[col].fillna(np.round(data_test[col].mean(),0), inplace = True)

In [ ]:
data_test_cat = data_test.select_dtypes(include =  ["object"])

In [ ]:
for col in data_test_cat.columns:
    lr = LabelEncoder()
#     set[col] = le.fit(data_train_cat[col])
    data_test[col+"_num"] = lr.fit_transform(data_test_cat[col])
#     print(col)

In [ ]:
testX = data_test.select_dtypes(exclude= ['object'])

In [ ]:
from xgboost import XGBRegressor

In [ ]:
model = XGBRegressor()
model.fit(trainX,trainY)

In [ ]:
testY = model.predict(testX)
testY

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
from sklearn.metrics import median_absolute_error

In [ ]:
len(data_test)

In [ ]:
trainY.dtype

In [ ]:
r2_score(trainY[:-1],testY)

In [ ]:
r2_score(testY,trainY[:-1])

In [ ]:
median_absolute_error(testY,trainY[:-1])

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data_train.plot.scatter(x= 'GrLivArea', y = 'SalePrice')